# ███████╗██╗  ██╗ █████╗ ███╗   ███╗██████╗ ██╗     ███████╗    ███╗   ███╗███████╗██╗  ██╗██████╗      ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝╚██╗██╔╝██╔══██╗████╗ ████║██╔══██╗██║     ██╔════╝    ████╗ ████║██╔════╝██║  ██║██╔══██╗    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# █████╗   ╚███╔╝ ███████║██╔████╔██║██████╔╝██║     █████╗      ██╔████╔██║█████╗  ███████║██████╔╝    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██╔══╝   ██╔██╗ ██╔══██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝      ██║╚██╔╝██║██╔══╝  ██╔══██║██╔══██╗    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ███████╗██╔╝ ██╗██║  ██║██║ ╚═╝ ██║██║     ███████╗███████╗    ██║ ╚═╝ ██║███████╗██║  ██║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
# ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 

# path to store all package configuration at
config-path = "~/test_config/"
# path or auto and omitting for automatically lookup of package manager
package-manager = "auto"

# list of packages to install
[packages]
    [packages.kitty]
        # version to look the package at
        version = "0.21.2"
        # configuration for the package
        [packages.kitty.config]

            # key is the path relative to 'config-path', specifies where to write
            # 'content' to
            [packages.kitty.config."kitty/kitty.conf"]
                content = """\
font_family Iosevka Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0
enable_audio_bell no
remember_window_size no
initial_window_width 82c
initial_window_height 24c
confirm_os_window_close 0
"""

    [packages.zathura]
        version = "0.4.9"
        [packages.zathura.config]
            [packages.zathura.config."zathura/zathurarc"]
                content = """\
set selection-clipboard clipboard
set window-title-basename "true"
set selection-clipboard "clipboard
"""

    [packages.nvim]
        version = "0.10.0"
        [packages.nvim.config]
            [packages.nvim.config."nvim/after/plugin/treesitter.lua"]
                content = """\
require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all"
  ensure_installed = { "c", "lua", "rust", "javascript", "css", "html", "markdown", "javascript"},

  -- Install parsers synchronously (only applied to `ensure_installed`)
  sync_install = false,

  -- Automatically install missing parsers when entering buffer
  -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
  auto_install = true,

  highlight = {
    -- `false` will disable the whole extension
    enable = true,
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}
"""

            [packages.nvim.config."nvim/coc-settings.json"]
                content = """\
{
    "diagnostic.checkCurrentLine": true,
        "coc.preferences.formatOnSave": true,
        "diagnostic.virtualText": true,
        "diagnostic.hintSign": "H",
        "diagnostic.infoSign": "I",
        "diagnostic.errorSign": "E",
        "diagnostic.warningSign": "W",
        "suggest.virtualText": true,
        "diagnostic.virtualTextCurrentLineOnly": false,
        "hover.floatConfig": {
            "border": true,
            "rounded": true
        },
        "ltex.language": "en-US",
        "suggest.enableFloat": true,
        "suggest.floatConfig": {
            "border": true,
            "rounded": true
        }
}
"""
