# ███████╗██╗  ██╗ █████╗ ███╗   ███╗██████╗ ██╗     ███████╗    ███╗   ███╗███████╗██╗  ██╗██████╗      ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝╚██╗██╔╝██╔══██╗████╗ ████║██╔══██╗██║     ██╔════╝    ████╗ ████║██╔════╝██║  ██║██╔══██╗    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# █████╗   ╚███╔╝ ███████║██╔████╔██║██████╔╝██║     █████╗      ██╔████╔██║█████╗  ███████║██████╔╝    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██╔══╝   ██╔██╗ ██╔══██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝      ██║╚██╔╝██║██╔══╝  ██╔══██║██╔══██╗    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ███████╗██╔╝ ██╗██║  ██║██║ ╚═╝ ██║██║     ███████╗███████╗    ██║ ╚═╝ ██║███████╗██║  ██║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
# ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝    ╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝

# specify a package manager to use, if 'auto' or empty fallback to auto
# detection
package-manager = "/usr/bin/pacman"

# configure all packages you require to be permanently installed on your system
[packages]
  [packages.kitty]
    # lock a package on a specific version, mehr will not install anything
    # higher or lower than this, throws an error if the repos of the used
    # package manager do not include the specific version
    version = "0.30.1"
  [packages.neovim]
   # packages without version or url are also installed

# configure your installed packages
[config]
  # top level configuration path, all other files are created relative to this
  # path, if empty falls back to `$XDG_CONFIG_HOME` for linux, %AppData% for
  # windows and $HOME/Library/Application Support/ for macOS
  path = "/home/teo/.config"
  [config.files]
    [config.files."i3/config"]
      # copies /etc/i3/config to /home/teo/.config/i3/config
      path = "/etc/i3/config"
    [config.files."i3status/i3status.conf"]
      # creates a soft link from /home/teo/.config/i3/config/i3status/i3status.conf to /etc/i3status.conf
      link = "/etc/i3status.conf"
    [config.files."kitty/kitty.conf"]
      # downloads content to /home/teo/.config/kitty/kitty.conf
      url = "https://raw.githubusercontent.com/xNaCly/dotfiles/master/kitty/kitty.conf"
    [config.files."zathura/zathurarc"]
      # writes the right hand site to /home/teo/.config/zathura/zathurarc
      content = """\
set selection-clipboard clipboard
set window-title-basename "true"         
set selection-clipboard "clipboard"\
"""
